version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        freshness: 
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        identifier: raw_gz_sales
        description: sales data
        tests:
        - unique:
            column_name: "(orders_id || pdt_id)"
        columns:
          - name: date_date
            description: date of sale
            tests:
              - not_null
          - name: orders_id
            description: unique order id
            tests:
              - not_null
          - name: pdt_id
            description: unique product id
            tests:
              - not_null
          - name: revenue
            description: revnue gained from transaction
            tests:
              - not_null
          - name: quantity
            description: quantity of product ordered
            tests:
              - not_null
            
            
      - name: product
        identifier: raw_gz_product
        description: product data
        columns:
          - name: products_id
            description: unique id of the product
            tests:
              - unique
              - not_null
          - name: purchse_price
            description: price per product
            tests:
              - not_null
                  
      - name: ship
        identifier: raw_gz_ship
        description: shipping data
        columns:
          - name: orders_id
            description: unique id of the order to be shipped
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: fee charged to customer for shipping
            tests:
              - not_null
          - name: logcost
            description: cost for logging to company
            tests:
              - not_null
          - name: ship_cost
            description: cost for shipping to the company
            tests:
              - not_null
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords campaign data
        tests:
        - unique:
            column_name: "(date_date || campaign_key)"
        columns:
          - name: date_date
            description: campaign date
            tests:
              - not_null
          - name: paid_source
            description: advertisement platform
            tests:
              - not_null
          - name: campaign_key
            description: key to identify different campaigns
            tests:
              - not_null
          - name: campgn_name
            description: name to define campaign
            tests:
              - not_null
          - name: ads_cost
            description: fee to company for advertising
            tests:
              - not_null
          - name: impression
            description: reach of advertising campaign
            tests:
              - not_null
          - name: click
            description: how many actually clicked
            tests:
              - not_null
      - name: bing
        identifier: raw_gz_bing
        description: bing campaign data
        tests:
        - unique:
            column_name: "(date_date || campaign_key)"
        columns:
          - name: date_date
            description: campaign date
            tests:
              - not_null
          - name: paid_source
            description: advertisement platform
            tests:
              - not_null
          - name: campaign_key
            description: key to identify different campaigns
            tests:
              - not_null
          - name: campgn_name
            description: name to define campaign
            tests:
              - not_null
          - name: ads_cost
            description: fee to company for advertising
            tests:
              - not_null
          - name: impression
            description: reach of advertising campaign
            tests:
              - not_null
          - name: click
            description: how many actually clicked
            tests:
              - not_null
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo campaign data
        tests:
        - unique:
            column_name: "(date_date || campaign_key)"
        columns:
          - name: date_date
            description: campaign date
            tests:
              - not_null
          - name: paid_source
            description: advertisement platform
            tests:
              - not_null
          - name: campaign_key
            description: key to identify different campaigns
            tests:
              - not_null
          - name: campgn_name
            description: name to define campaign
            tests:
              - not_null
          - name: ads_cost
            description: fee to company for advertising
            tests:
              - not_null
          - name: impression
            description: reach of advertising campaign
            tests:
              - not_null
          - name: click
            description: how many actually clicked
            tests:
              - not_null
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook campaign data
        tests:
        - unique:
            column_name: "(date_date || campaign_key)"
        columns:
          - name: date_date
            description: campaign date
            tests:
              - not_null
          - name: paid_source
            description: advertisement platform
            tests:
              - not_null
          - name: campaign_key
            description: key to identify different campaigns
            tests:
              - not_null
          - name: campgn_name
            description: name to define campaign
            tests:
              - not_null
          - name: ads_cost
            description: fee to company for advertising
            tests:
              - not_null
          - name: impression
            description: reach of advertising campaign
            tests:
              - not_null
          - name: click
            description: how many actually clicked
            tests:
              - not_null

models:
  - name: finance_campaigns_month
    columns:
      - name: campaign_year
        description: year in question
        tests:
          - not_null